set define off
whenever sqlerror exit sql.sqlcode

prompt Seeding local Fusion reference cache and demo supplier requests.

insert into fusion_supplier_ref (
  fusion_supplier_id,
  supplier_number,
  supplier_name,
  supplier_name_normalized,
  supplier_type,
  active,
  source_last_updated_at,
  last_seen_sync_id
) values (
  'FUS-1001',
  'SUP-1001',
  'Atlas Packaging LLC',
  supplier_projection_pkg.normalize_text('Atlas Packaging LLC'),
  'COMPANY',
  'Y',
  systimestamp,
  'SYNC-SEED-001'
);

insert into fusion_supplier_tax_ref (
  fusion_tax_reference_id,
  fusion_supplier_id,
  country_code,
  tax_type,
  tax_id_fingerprint,
  tax_id_masked,
  active,
  source_last_updated_at,
  last_seen_sync_id
) values (
  'TAX-1001',
  'FUS-1001',
  'PK',
  'NTN',
  supplier_projection_pkg.fingerprint('PK-NTN-445566'),
  supplier_projection_pkg.mask_identifier('PK-NTN-445566'),
  'Y',
  systimestamp,
  'SYNC-SEED-001'
);

insert into fusion_supplier_site_ref (
  fusion_supplier_site_id,
  fusion_supplier_id,
  site_name,
  site_number,
  country_code,
  address_line1,
  city,
  address_normalized,
  email_domain,
  phone_normalized,
  active,
  source_last_updated_at,
  last_seen_sync_id
) values (
  'SITE-1001',
  'FUS-1001',
  'Karachi Main',
  'KHI-01',
  'PK',
  '12 Industrial Area',
  'Karachi',
  supplier_projection_pkg.normalize_text('12 Industrial Area Karachi PK'),
  'atlaspack.example',
  '92211234567',
  'Y',
  systimestamp,
  'SYNC-SEED-001'
);

insert into fusion_supplier_bank_ref (
  fusion_bank_account_id,
  fusion_supplier_id,
  bank_country_code,
  currency_code,
  bank_account_fingerprint,
  bank_account_last_four,
  active,
  source_last_updated_at,
  last_seen_sync_id
) values (
  'BANK-1001',
  'FUS-1001',
  'PK',
  'PKR',
  supplier_projection_pkg.fingerprint('PK-IBAN-445566778899'),
  '8899',
  'Y',
  systimestamp,
  'SYNC-SEED-001'
);

insert into supplier_request (
  request_id,
  request_number,
  requester_subject_id,
  requester_display_name,
  requester_email,
  status,
  request_version,
  supplier_name,
  supplier_name_normalized,
  supplier_type,
  country_code,
  address_line1,
  address_line2,
  city,
  postal_code,
  address_normalized,
  contact_person,
  contact_email,
  contact_phone,
  business_unit,
  product_service_category,
  business_justification,
  expected_annual_spend,
  currency_code,
  base_currency_code,
  base_currency_amount,
  conversion_rate,
  tax_registration_number,
  tax_registration_fingerprint,
  tax_registration_masked,
  bank_account_fingerprint,
  bank_account_last_four,
  bank_country_code,
  bank_currency_code,
  site_name,
  site_address_line1,
  site_city,
  site_country_code,
  risk_score,
  risk_level,
  duplicate_level,
  submitted_at
) values (
  1,
  'REQ-SEED-001',
  'REQ_AMINA_SUB',
  'Amina Requester',
  'amina.requester@example.com',
  'UNDER_REVIEW',
  1,
  'Atlas Packaging LLC',
  supplier_projection_pkg.normalize_text('Atlas Packaging LLC'),
  'COMPANY',
  'PK',
  '12 Industrial Area',
  'Block 7',
  'Karachi',
  '74000',
  supplier_projection_pkg.normalize_text('12 Industrial Area Karachi PK'),
  'Nadia Khan',
  'nadia@atlaspack.example',
  '+92 21 1234567',
  'PROCUREMENT',
  'Packaging Materials',
  'Packaging supplier needed for recurring warehouse shipments.',
  275000,
  'USD',
  'USD',
  275000,
  1,
  'PK-NTN-445566',
  supplier_projection_pkg.fingerprint('PK-NTN-445566'),
  supplier_projection_pkg.mask_identifier('PK-NTN-445566'),
  supplier_projection_pkg.fingerprint('PK-IBAN-445566778899'),
  '8899',
  'PK',
  'PKR',
  'Karachi Main',
  '12 Industrial Area',
  'Karachi',
  'PK',
  48,
  'HIGH',
  'EXACT',
  systimestamp
);

insert into request_assessment (
  assessment_id,
  request_id,
  request_version,
  is_latest,
  validation_status,
  validation_results_json,
  duplicate_level,
  duplicate_matches_json,
  risk_score,
  risk_level,
  risk_factors_json,
  reference_sync_id,
  assessed_by_subject_id
) values (
  1,
  1,
  1,
  'Y',
  'WARNING',
  '[{"field":"duplicate","severity":"WARNING","blocking":false,"message":"Exact Fusion reference match requires reviewer decision"}]',
  'EXACT',
  '[{"match_type":"EXACT","supplier_number":"SUP-1001","duplicate_points":45,"tax_match_count":1,"bank_match_count":1}]',
  48,
  'HIGH',
  '[{"rule_code":"EXACT_TAX_ID_MATCH","configured_weight":45,"applied_weight":45,"evidence":"Exact tax fingerprint match found"},{"rule_code":"HIGH_EXPECTED_SPEND","configured_weight":5,"applied_weight":3,"evidence":"Expected annual spend is between 250000 and 500000"}]',
  'SYNC-SEED-001',
  'SYSTEM'
);

insert into ai_assessment (
  ai_assessment_id,
  request_id,
  request_version,
  is_latest,
  summary,
  recommended_actions,
  justification_quality,
  model_name,
  status
) values (
  1,
  1,
  1,
  'Y',
  'Gemini advisory summary: justification is understandable, but duplicate evidence should be reviewed.',
  'Check exact duplicate evidence and either mark duplicate or approve with documented reason.',
  'MEDIUM',
  'gemini-prototype',
  'SUCCEEDED'
);

insert into action_history (
  action_history_id,
  request_id,
  action,
  from_status,
  to_status,
  reason,
  actor_subject_id
) values (
  1,
  1,
  'VALIDATION_PASSED',
  'SUBMITTED',
  'UNDER_REVIEW',
  'Seed request routed to reviewer queue',
  'SYSTEM'
);

insert into integration_job (
  job_id,
  request_id,
  integration_type,
  status,
  attempt_number,
  payload_reference,
  response_reference,
  retryable,
  completed_at
) values (
  1,
  1,
  'AI_EXPLANATION',
  'SUCCEEDED',
  1,
  'REQUEST:1:VERSION:1',
  'AI_ASSESSMENT:1',
  'N',
  systimestamp
);

insert into supplier_request (
  request_id,
  request_number,
  requester_subject_id,
  requester_display_name,
  requester_email,
  status,
  request_version,
  supplier_name,
  supplier_name_normalized,
  supplier_type,
  country_code,
  address_line1,
  city,
  address_normalized,
  contact_person,
  contact_email,
  business_unit,
  product_service_category,
  business_justification,
  expected_annual_spend,
  currency_code,
  base_currency_code,
  base_currency_amount,
  conversion_rate,
  risk_score,
  risk_level,
  duplicate_level
) values (
  2,
  'REQ-SEED-002',
  'REQ_AMINA_SUB',
  'Amina Requester',
  'amina.requester@example.com',
  'CORRECTION_REQUIRED',
  2,
  'Nova Office Supplies',
  supplier_projection_pkg.normalize_text('Nova Office Supplies'),
  'COMPANY',
  'US',
  '88 Market Street',
  'Austin',
  supplier_projection_pkg.normalize_text('88 Market Street Austin US'),
  'Mark Ellis',
  'mark@novaoffice.example',
  'PROCUREMENT',
  'Office Supplies',
  'Need supplies.',
  45000,
  'USD',
  'USD',
  45000,
  1,
  15,
  'LOW',
  'NONE'
);

insert into action_history (
  action_history_id,
  request_id,
  action,
  from_status,
  to_status,
  reason,
  actor_subject_id
) values (
  2,
  2,
  'REQUEST_CORRECTION',
  'UNDER_REVIEW',
  'CORRECTION_REQUIRED',
  'Business justification is too vague; requester should add purchase context.',
  'REV_PRIYA_SUB'
);

insert into supplier_request (
  request_id,
  request_number,
  requester_subject_id,
  requester_display_name,
  requester_email,
  status,
  request_version,
  supplier_name,
  supplier_name_normalized,
  supplier_type,
  country_code,
  address_line1,
  address_line2,
  city,
  postal_code,
  address_normalized,
  contact_person,
  contact_email,
  business_unit,
  product_service_category,
  business_justification,
  expected_annual_spend,
  currency_code,
  base_currency_code,
  base_currency_amount,
  conversion_rate,
  tax_registration_number,
  tax_registration_fingerprint,
  tax_registration_masked,
  risk_score,
  risk_level,
  duplicate_level,
  fusion_create_error
) values (
  3,
  'REQ-SEED-003',
  'REQ_AMINA_SUB',
  'Amina Requester',
  'amina.requester@example.com',
  'INTEGRATION_FAILED',
  1,
  'Cedar Logistics',
  supplier_projection_pkg.normalize_text('Cedar Logistics'),
  'COMPANY',
  'AE',
  '21 Port Road',
  'Suite 3',
  'Dubai',
  '00000',
  supplier_projection_pkg.normalize_text('21 Port Road Dubai AE'),
  'Sara Ali',
  'sara@cedarlogistics.example',
  'LOGISTICS',
  'Freight',
  'Freight supplier required for cross-border delivery.',
  125000,
  'USD',
  'USD',
  125000,
  1,
  'AE-TAX-9988',
  supplier_projection_pkg.fingerprint('AE-TAX-9988'),
  supplier_projection_pkg.mask_identifier('AE-TAX-9988'),
  22,
  'MEDIUM',
  'NONE',
  'Fusion endpoint timeout'
);

insert into integration_job (
  job_id,
  request_id,
  integration_type,
  status,
  attempt_number,
  payload_reference,
  error_type,
  error_message,
  retryable,
  completed_at
) values (
  2,
  3,
  'FUSION_CREATE',
  'FAILED',
  1,
  'REQUEST:3:APPROVED',
  'TIMEOUT',
  'Fusion endpoint timeout',
  'Y',
  systimestamp
);

commit;
